"""Intelligence layer rule engine for NGX AI Advisor recommendations.

This module converts model probabilities, sentiment, risk, and sector context
into a final investment action. It connects upstream ML/NLP/risk services to
downstream explanation generation, persistence, and FastAPI recommendation
responses.
"""

from __future__ import annotations

import logging
import os
from dataclasses import dataclass, field
from datetime import date

from dotenv import load_dotenv

from app.utils.enums import RecommendationAction, SignalStrength

logger = logging.getLogger(__name__)

load_dotenv()


@dataclass(frozen=True)
class SignalInput:
    """Inputs required to evaluate a stock recommendation."""

    ticker: str
    xgb_probability: float | None = None
    lstm_probability: float | None = None
    sentiment_score: float = 0.0
    risk_score: float = 50.0
    sector_adjustment: float = 0.0
    volatility_flag: bool = False
    as_of_date: date | None = None


@dataclass(frozen=True)
class SignalOutput:
    """Final signal generated by the rule engine."""

    ticker: str
    date: date
    recommendation: RecommendationAction
    confidence: float
    risk_score: float
    signal_strength: SignalStrength
    ensemble_prob: float
    reasons: list[str] = field(default_factory=list)


class RuleEngine:
    """Evaluate BUY/HOLD/SELL/AVOID/WATCHLIST signals from model and market inputs."""

    def __init__(self, xgb_weight: float | None = None, lstm_weight: float | None = None) -> None:
        """Create a rule engine with configurable ensemble weights."""

        self.xgb_weight = self._env_float("XGB_ENSEMBLE_WEIGHT", 0.60) if xgb_weight is None else xgb_weight
        self.lstm_weight = self._env_float("LSTM_ENSEMBLE_WEIGHT", 0.40) if lstm_weight is None else lstm_weight
        self._validate_weights()
        logger.info(
            "RuleEngine configured with xgb_weight=%.2f, lstm_weight=%.2f",
            self.xgb_weight,
            self.lstm_weight,
        )

    def evaluate(self, signal: SignalInput) -> SignalOutput:
        """Return the final recommendation for one stock signal input."""

        ticker = signal.ticker.upper().strip()
        if not ticker:
            raise ValueError("SignalInput.ticker cannot be empty")

        risk_score = self._bounded(signal.risk_score, 0.0, 100.0)
        sentiment_score = self._bounded(signal.sentiment_score, -1.0, 1.0)
        sector_adjustment = self._bounded(signal.sector_adjustment, -0.15, 0.15)

        ensemble_prob, ensemble_reasons = self._ensemble_probability(signal)
        adjusted_prob = self._bounded(ensemble_prob + (sentiment_score * 0.10) + sector_adjustment, 0.0, 1.0)

        reasons = list(ensemble_reasons)
        reasons.append(f"Base ensemble probability: {ensemble_prob:.3f}")
        if sentiment_score:
            reasons.append(f"Sentiment adjustment applied: {sentiment_score * 0.10:+.3f}")
        if sector_adjustment:
            reasons.append(f"Sector adjustment applied: {sector_adjustment:+.3f}")

        recommendation = self._recommend(adjusted_prob, risk_score)
        if signal.volatility_flag and recommendation == RecommendationAction.BUY:
            logger.warning("Volatility override changed BUY to HOLD for %s", ticker)
            recommendation = RecommendationAction.HOLD
            reasons.append("Volatility override: BUY downgraded to HOLD")
        elif risk_score >= 85 and recommendation in {RecommendationAction.BUY, RecommendationAction.WATCHLIST}:
            logger.warning("Extreme risk override changed %s to AVOID for %s", recommendation.value, ticker)
            recommendation = RecommendationAction.AVOID
            reasons.append("Extreme risk override: risk score is above 85")

        confidence = self._confidence(adjusted_prob, risk_score, signal.volatility_flag)
        signal_strength = self._signal_strength(adjusted_prob, confidence)
        reasons.append(f"Adjusted probability after context: {adjusted_prob:.3f}")
        reasons.append(f"Risk score: {risk_score:.1f}/100")

        logger.info(
            "Evaluated %s: %s confidence=%.1f risk=%.1f prob=%.3f",
            ticker,
            recommendation.value,
            confidence,
            risk_score,
            adjusted_prob,
        )
        return SignalOutput(
            ticker=ticker,
            date=signal.as_of_date or date.today(),
            recommendation=recommendation,
            confidence=round(confidence, 1),
            risk_score=round(risk_score, 1),
            signal_strength=signal_strength,
            ensemble_prob=round(adjusted_prob, 3),
            reasons=reasons,
        )

    def _ensemble_probability(self, signal: SignalInput) -> tuple[float, list[str]]:
        """Blend available model probabilities without requiring both models."""

        model_probs: list[tuple[str, float, float]] = []
        reasons: list[str] = []
        if signal.xgb_probability is not None:
            model_probs.append(("XGBoost", self._bounded(signal.xgb_probability, 0.0, 1.0), self.xgb_weight))
        if signal.lstm_probability is not None:
            model_probs.append(("LSTM", self._bounded(signal.lstm_probability, 0.0, 1.0), self.lstm_weight))

        if not model_probs:
            logger.warning("No model probabilities supplied; using neutral ensemble probability")
            reasons.append("No model probabilities supplied; neutral probability used")
            return 0.50, reasons

        total_weight = sum(weight for _, _, weight in model_probs)
        probability = sum(prob * weight for _, prob, weight in model_probs) / total_weight
        for model_name, prob, weight in model_probs:
            reasons.append(f"{model_name} probability {prob:.3f} with normalized weight {weight / total_weight:.2f}")
        return probability, reasons

    def _recommend(self, probability: float, risk_score: float) -> RecommendationAction:
        """Map adjusted probability and risk score into a recommendation action."""

        if probability >= 0.68 and risk_score < 65:
            return RecommendationAction.BUY
        if probability >= 0.58 and risk_score < 75:
            return RecommendationAction.WATCHLIST
        if probability <= 0.32 and risk_score >= 70:
            return RecommendationAction.AVOID
        if probability <= 0.42:
            return RecommendationAction.SELL
        return RecommendationAction.HOLD

    def _confidence(self, probability: float, risk_score: float, volatility_flag: bool) -> float:
        """Calculate confidence as probability distance from neutral, penalized by risk."""

        directional_certainty = abs(probability - 0.50) * 200
        risk_penalty = max(0.0, (risk_score - 50.0) * 0.35)
        volatility_penalty = 8.0 if volatility_flag else 0.0
        confidence = 50.0 + directional_certainty - risk_penalty - volatility_penalty
        return self._bounded(confidence, 1.0, 99.0)

    def _signal_strength(self, probability: float, confidence: float) -> SignalStrength:
        """Return a strength label for the adjusted recommendation signal."""

        distance = abs(probability - 0.50)
        if confidence >= 70 and distance >= 0.18:
            return SignalStrength.STRONG
        if confidence >= 58 and distance >= 0.08:
            return SignalStrength.MODERATE
        return SignalStrength.WEAK

    def _validate_weights(self) -> None:
        """Validate ensemble weight configuration."""

        if self.xgb_weight < 0 or self.lstm_weight < 0:
            raise ValueError("Ensemble weights cannot be negative")
        if self.xgb_weight + self.lstm_weight <= 0:
            raise ValueError("At least one ensemble weight must be positive")

    @staticmethod
    def _env_float(name: str, default: float) -> float:
        """Read a float environment variable with a safe default."""

        raw_value = os.getenv(name)
        if raw_value is None:
            return default
        try:
            return float(raw_value)
        except ValueError:
            logger.warning("Invalid %s=%r; using default %.2f", name, raw_value, default)
            return default

    @staticmethod
    def _bounded(value: float, lower: float, upper: float) -> float:
        """Clamp a numeric value into an inclusive range."""

        return max(lower, min(upper, float(value)))
